<?php
/**
 * WP-W2-07 — QR page seed data (generated by scripts/build_w2_07_qr_data.py).
 * DO NOT EDIT BY HAND. Regenerate from the team_40 content export.
 * Map: child-slug => array( 'title' => str, 'html' => str ).
 */
defined( 'ABSPATH' ) || exit;

return array(
	'qr1' => array(
		'title' => 'והקדמת - qr1',
		'html'  => '<div></div>
<div></div>
<div></div>
<div>זה פשוט מאוד.</div>
<div>46 סיפורים - רובם מהבלוג שכתבתי במשך 5 שנים, חלקם ממופע הסיפורים שלי וחלקם חדשים דנדשים.</div>
<div>כולם מחיי הפרטיים.</div>
<div></div>
<div>רק אם בא לכם, בסוף כל סיפור מופיע קוד QR לסריקה בנייד, או כתובת אינטרנט קצרה להקלדה, שיעבירו אתכם לדף נסתר באתר. בדף הזה תמצאו תוספת לאותו סיפור שקראתם, או וידאו חזק מהרשת שקשור לנושא. בדף הזה יש גם אפשרות להגיב, לפגוש אנשים אחרים שכמוכם קראו את הסיפור הזה וסרקו את הקוד. גם אני אהיה שם ואשמח לפגוש אתכם.</div>
<div></div>
<div>באהבה ובתודה גדולה.</div>
<div>אייל</div>',
	),
	'qr2' => array(
		'title' => 'qr2 - אקדח לתוך הראש',
		'html'  => 'קבלו קטע קצר מתוך הסרט "<a href="https://he.wikipedia.org/wiki/%D7%A2%D7%99%D7%A8_%D7%94%D7%90%D7%9C%D7%95%D7%94%D7%99%D7%9D_(%D7%A1%D7%A8%D7%98)"><strong>עיר האלוהים</strong></a>" (מומלץ בחום רב למי שלא ראה!)

בקטע שלפניכם אין תרגום, אבל לא ממש צריך תרגום כדי להבין מה קורה.

בגדול: פאבלה, שתי כנופיות, סגירת חשבון.

האצבע על ההדק מאוד קלה בברזיל. ככה זה בסרט. תאמינו או לא, ככה זה גם במציאות! ברגעים אלה ממש!

(הקטע קשה מאוד לצפיה – ראו הוזהרתם!!!!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/ng9q5-xkNmE" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

 "מבוהל. משותק. מצומרר בכל הגוף..". מסתבר שאלי קפץ לביקור גם בצהריים. אפילו לא הרגשתי כשצילם עם פלאש. תמונה שווה אלף מילים. האומנם?

&nbsp;

&nbsp;

&nbsp;

 כן, זה בכדור הארץ. בבוליביה ליתר דיוק. נופים עוצרי נשימה. הוספתי גם אני אבן למגדל. איך אפשר שלא – "יוסי מגולני היה פה" צרוב בתודעה הקולקטיבית של כולנו.

 לה-פאז. פאבלה אחת גדולה. לגטאות של העשירים אי אפשר להיכנס.

&nbsp;

&nbsp;

&nbsp;

 צ\'ולות מוכרות את מרכולתן. את עלי הקוקה אפשר להריח גם דרך מסך המחשב! התאריך על התמונה אמיתי לגמרי.

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

 איפה החוטיני? איפה הבקיני? אין ספק, הגעתי למקום הכי א-מיני בכדור הארץ.

&nbsp;

&nbsp;

&nbsp;

&nbsp;



לכל בית יש מרפסת ולכל צ\'ולה תינוק קשור על הגב.

<a href="/books/%D7%A6%D7%91%D7%A2-%D7%91%D7%9B%D7%97%D7%95%D7%9C-%D7%95%D7%96%D7%A8%D7%95%D7%A7-%D7%9C%D7%99%D7%9D/"></a> ראה אור בשנת 2001. <a href="/books/%D7%A6%D7%91%D7%A2-%D7%91%D7%9B%D7%97%D7%95%D7%9C-%D7%95%D7%96%D7%A8%D7%95%D7%A7-%D7%9C%D7%99%D7%9D/">לדף הספר&gt;&gt;</a>

&nbsp;

&nbsp;

 המעגל נסגר. הפצע הגליד. ברזיל יפה. ברזיל מדהימה.

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

 חולם רק על היום שאחזור אליה!!!',
	),
	'qr3' => array(
		'title' => 'qr3 - האלמנה השחורה',
		'html'  => 'אחד הסרטים הכי חזקים שתראו ביוטיוב.

פשוט צפו בו.

אי אפשר להעביר את המסר חזק וברור יותר!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/TYIxBRA5qjA" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr4' => array(
		'title' => 'qr4 - בום-בום-בום על דלתי מרום',
		'html'  => 'הרצוג 23 גבעתיים

בימים יפים יותר.

גורד השחקים הגבוה ביותר בגבעתיים של אז.

אנחנו בקומה שנייה מימין.',
	),
	'qr5' => array(
		'title' => 'qr5 - אלכסון הוא אסון',
		'html'  => 'קצת נוסטלגיה בשחור לבן,

קבלו את דובי-דובי דוברמן

ד"ר לחוקי תנועה

בפרק משעשע במיוחד

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/u7fkhPLP2wg" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr6' => array(
		'title' => 'qr6 - ספיבאק',
		'html'  => '<em>2:07 דקות שמסבירות בצ\'יק את כל תסבוכת עלילת המחזה. </em>

<em>אם סופוקלס היה רואה את הסרטון הזה הוא בטוח היה נגנב. </em>

<em>לפחות כמוני.</em>

<em>למה לא היה יוטיוב בשנות התשעים?!?!?! ;-)</em>

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/7DjazW1AqH8" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr7' => array(
		'title' => 'qr7 - אחד לשלושה',
		'html'  => 'הגאון בפעולה

לואיס סי. קיי. – על נישואין וגירושין

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/SoRKaq8VhOU" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr8' => array(
		'title' => 'qr8 - סופה במדבר',
		'html'  => 'מבזק החדשות הראשון אחרי נפילת הטילים הראשונה.

נחמן שי, המרגיע הלאומי במלוא הדרו ותפארתו:

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/kr9Izd_g588" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr9' => array(
		'title' => 'qr9 - טיפול שורש',
		'html'  => 'שלושה סרטונים מעוררי השראה, אימה וזוועה שיזכירו לכם מדוע כדאי לצחצח שיניים טוב טוב!!!!

עם פלואור או בלי פלואור - זאת השאלה!

חחח ;-)

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/JBsZ5fbZ0QY" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/7_oQRFaNzwY" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/bTGl17k1kFM" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr10' => array(
		'title' => 'qr10 - וואט איז דאט?',
		'html'  => 'תאמינו או לא, יש עכשיו מישהו שישמח מאוד לשמוע את קולכם!

גם שיחת "מה נשמע", "מה שלומך" ו-"איך אתה מרגיש" תהיה סבבה לגמרי.

צלצלו עכשיו.

בעצם, צפו קודם בוידאו.

<span style="color: #ffffff;">/</span>

<span style="color: #ffffff;">/</span>

<span style="color: #ffffff;">/</span><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/bdJQOIeQBig" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>ואם גם הוידאו הזה לא גרם לכם עכשיו להרים את השפופרת ולחייג (מילים שכבר חלפו מן העולם, באווירת הנושא פה),

קראו את מכתב הפרידה של גבי למטה. נראה לי הוא כבר יעשה את העבודה.
<div class="" data-block="true" data-editor="49db9" data-offset-key="ekku5-0-0"><span style="color: #ffffff;"> \\</span></div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="2vr3n-0-0">
<div class="_1mf _1mj" data-offset-key="2vr3n-0-0">
<h3 class="_1mf _1mk" data-offset-key="b40p4-0-0"><strong>לגזור ולשמור!</strong></h3>
<div class="_1mf _1mk" data-offset-key="b40p4-0-0">לקום כל בוקר ולשנן את הטקסט הבא טוב-טוב!</div>
</div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="b40p4-0-0">
<div class="_1mf _1mk" data-offset-key="b40p4-0-0"><span data-offset-key="b40p4-0-0">מכתב פרידה שכתב הסופר <strong>גבריאל גרסיה מארקס</strong>. </span></div>
<div class="_1mf _1mk" data-offset-key="b40p4-0-0"><span data-offset-key="b40p4-0-0">סוג של צוואה רוחנית.</span></div>
<div class="_1mf _1mk" data-offset-key="b40p4-0-0">אם אתם שואלים אותי, הנוסח האמיתי והנכון של <strong>"ברכת הדרך" לחיים:</strong></div>
<div class="_1mf _1mk" data-offset-key="b40p4-0-0"></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="25uls-0-0">
<div class="_1mf _1mk" data-offset-key="25uls-0-0">----------------------------------------------------------------------------------</div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="e0tk7-0-0">
<div class="_1mf _1mk" data-offset-key="e0tk7-0-0"><span style="color: #ff0000;"><em>"אם לרגע אלוהים היה שוכח כי אני רק בובת סמרטוטים, והיה מעניק לי במתנה פרק חיים, הייתי מנצל זמן זה עד כמה שהייתי יכול.</em></span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="6memr-0-0">
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>יתכן שלא הייתי אומר כל מה שאני חושב, אבל בוודאות הייתי חושב על כל מה שאני אומר. </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>הייתי מעריך את הדברים, לא לפי שוויים, אלא לפי ערכם. </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>הייתי ישן מעט, חולם יותר. </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>אני מבין שעל כל דקה שאנו עוצמים עיניים, אנו מפסידים שישים שניות של אור. </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>הייתי מתהלך במקומות בהם האחרים נעצרו, </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>הייתי מתעורר בזמן שהאחרים ישנים. </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>אם אלוהים היה מעניק לי במתנה פרק חיים, הייתי מתלבש בפשטות, </em></span></div>
<div class="_1mf _1mk" data-offset-key="6memr-0-0"><span style="color: #ff0000;"><em>הייתי משתרע מול השמש, חשוף לא רק בגופי אלא גם בנשמתי.</em></span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="4tnbi-0-0">
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>הייתי מוכיח לאנשים עד כמה הם טועים בחושבם שהם מפסיקים להתאהב בהזדקנותם מבלי לדעת שמזדקנים ברגע שמפסיקים להתאהב! </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>לילד הייתי נותן כנפיים, אבל משאיר אותו ללמוד בכוחות עצמו לעוף. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>לזקנים הייתי מלמד שהמוות לא מגיע עם הזקנה אלא עם השכחה. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>הרבה דברים למדתי מכם, האנשים… למדתי שכל העולם רוצה לחיות על פסגת ההר, מבלי לדעת שהאושר האמיתי טמון בצורת העלייה במעלה ההר. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>למדתי שכשתינוק תופס בידו בפעם הראשונה את אצבע אביו, הוא מחזיק אותו לתמיד. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>למדתי שלאדם יש זכות להביט כלפי מטה בזולת רק כאשר הוא עומד לעזור לו להתרומם. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>כל-כך הרבה דברים הצלחתי ללמוד ממכם , אבל באמת - הם לא יעזרו לי, משום שכשישימו אותי בתוך הארון, למרבה הצער כבר לא אהיה בחיים. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>אילו הייתי יודע שהיום תהיה הפעם האחרונה בה אראה אותך ישן, הייתי מחבק אותך בחוזקה ומתפלל לאלוהים שאוכל להיות שומר נפשך. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>אילו הייתי יודע שאלו הם רגעי האחרונים לראותך, הייתי אומר "אני אוהב אותך "מבלי להניח, בטיפשות, שזה כבר ידוע לך. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>תמיד קיים המחר והחיים נותנים לנו הזדמנות נוספת בכדי לעשות את הדברים היטב, אבל במקרה שאני טועה והיום הוא כל מה שנשאר לנו, הייתי רוצה להגיד לך עד כמה אני אוהב אותך, </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>ושלעולם לא אשכחך. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>המחר לא מובטח לאף אחד, </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>צעיר או זקן. </em></span></div>
<div class="_1mf _1mk" data-offset-key="4tnbi-0-0"><span style="color: #ff0000;"><em>היום יכולה להיות הפעם האחרונה שתראה את אהוביך.</em></span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="7279m-0-0">
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>בגלל זה אל תחכה יותר, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>עשה היום, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>כי אם המחר לעולם לא יגיע, בוודאי תתחרט על היום בו לא הקדשת זמן לחיוך, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>לחיבוק, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>לנשיקה </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>והיית עסוק מכדי להגשים להם בקשה אחרונה. </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>שמור את אהוביך קרוב, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>תלחש באזנם עד כמה אתה זקוק להם, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>תאהב ותתייחס טוב אליהם, </em></span></div>
<div class="_1mf _1mk" data-offset-key="7279m-0-0"><span style="color: #ff0000;"><em>תקדיש זמן להגיד להם "אני מצטער ", </em></span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="68t32-0-0">
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>"סליחה", </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>"בבקשה", </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>"תודה", </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>וכל אותן מילות האהבה שאתה מכיר. </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>אף אחד לא יזכור אותך בשל מחשבותיך הנסתרות. </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>בקש מאלוהים את הכוח והחכמה לבטא אותם. </em></span></div>
<div class="_1mf _1mk" data-offset-key="68t32-0-0"><span style="color: #ff0000;"><em>תראה לחבריך ולאהוביך עד כמה הם חשובים לך."</em></span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="bsgc7-0-0">
<div class="_1mf _1mk" data-offset-key="bsgc7-0-0"><span data-offset-key="bsgc7-0-0"> </span></div>
</div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="75r4j-0-0"><span style="color: #ffffff;"> \\</span></div>
<div class="" data-block="true" data-editor="49db9" data-offset-key="75r4j-0-0"><span style="color: #ffffff;">/</span></div>
<strong>יאללה, תתקשר!</strong>

<strong>תתקשרי!</strong>

<strong>תגידי לסבא שאת אוהבת אותו.</strong>

<strong>תגיד לסבתא שאתה אוהב אותה.</strong>

<strong>תעשו להם את היום.</strong>

<span style="color: #ffffff;">/</span>

<span style="color: #ffffff;">/</span>

ואגב, אם אתם עדיין פה.. עוד כמה מילים בענייני "הורות" –

על דבר אחד אני משוכנע שנסכים כולנו: הילדים שלנו הם המראַה שלנו.

ואם משהו אצלם "לא בסדר", כדאי שנבדוק תחילה את עצמנו.

קבלו שני סרטונים חזקים ביותר.

הסרטון \'Alike\' אגב, זכה ב-64 פרסים!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/kQjtK32mGJQ" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/BlqT-V_CTcg" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr11' => array(
		'title' => 'qr11 - חורשט זבזי',
		'html'  => 'תאכלס, אז איך מכינים גונדי וחורשט זבזי אסליים?

לטבעונים בחבורה, <a href="http://saloona.co.il/rotteml/?p=1376?ref=blog_tags">הנה מתכון לגרסה הצמחונית&gt;&gt;</a>

בתאבון

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/w-D0VCXttRo" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/AgguPFBdqzM" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr12' => array(
		'title' => 'qr12 - אינדיאנה ג\'ונס והמכרה הארור',
		'html'  => '<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/KGucRKqYFuc" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>המכרה בפוטוסי בשיא תפארתו.

קליפ יחסית חדש.

בפוטוסי של 1999 המראות היו עוד יותר מטורפים.

עדיין, תחושת החנק והווייב הכללי עוברים לא רע.

קחו הרבה אוויר!

&nbsp;

 סיגריות, עלי קוקה, וודקה, אלכהול 90%, סרטים צבעוניים – הכל הולך. רק שהדיאבלו יהיה מבסוט.

 מאוד נדיר לפגוש פנים מחייכות במכרה. עבורם קוקה-קולה יותר טובה מאורגזמה!

 ילדה שפגשתי בכניסה למכרות. גם היא עובדת 8 שעות.
<p style="text-align: center;"></p>
<p style="text-align: center;">משכורת של פחות מדולר ליום. 100שקל לחודש! שוקל לשלוח קורות חיים.</p>',
	),
	'qr13' => array(
		'title' => 'qr13 - ואהבתָ',
		'html'  => 'כדי להיפרד מהחיים לא חייבים לטפס על קיר קרח בגובה 30 מטר. ברוך השם, לא חסרות דרכים לעזוב את העולם הזה...

קבלו סרטון חילוץ מסוג אחר. חילוץ של גוזל עורב, שבסך הכל ירד לשתות מים בבריכה שלנו בחצר, החליק וכמעט טבע. דרמה מטורפת שהתרחשה אצלנו בחצר הבית והפכה לסרטון קצר ומרגש שצילמתי וערכתי על מסירות, חברות ואהבת אמת.

דבורים, שפיריות, לפעמים גם שלדגים – את כל אלה אנחנו פוגשים על בסיס קבוע בבריכה בחצר, אבל בשבוע שעבר הגיע אורח חדש (ואולי אורחת, אנחנו לא בטוחים): אורח שבא לשתות מים בשרב הכבד וכמעט מצא את מותו. אחרי ארבע שעות של טיפול מסור ואוהב בידי הילדים הוא התאושש, פרש כנפיים ועף. תודה לאל.

מה שמדהים בכל הסיפור הזה היה לראות, ובעיקר לשמוע, את ההורים שלו מלמעלה, על צמרות העצים, שלא הרפו ולא עזבו את המקום לשנייה. במשך ארבע שעות חגו במעגלים מעלינו וזעקו לעזרה. תוכים ועורבים נוספים הגיעו מכל עבר ולא עזבו את המקום, עד שראו במו עיניהם את חברם פורש כנפיים ועף. לא יודע מה איתכם, אבל אני פה עם דמעות בעיניים.

השיר "לוחם ותיק" של אברהם טל כאילו נכתב במיוחד לסרטון הזה.

בחיאת אנשים, אנחנו למדנו את הלקח: 100 שקל ויש לכם אחלה כיסוי לבריכה. תשתמשו בו.
אהבה לכולכם וגם לעורביטולי – חברם החדש של הילדים, שמדי פעם עוצר בחצר להגיד שלום. מי יודע, אולי גם להגיד תודה.

<span style="color: #ffffff;">/</span>
<p style="text-align: right;">לצפיה בקליפ המרגש שערכתי <a href="https://drive.google.com/file/d/0B7h3db7B30CedE96N0U2TDlfdEU/view?usp=sharing" target="_blank" rel="noopener noreferrer">לחצו כאן </a>או על התמונה למטה.</p>
<p style="text-align: right;">שיר בפסקול: לוחם ותיק/אברהם טל</p>
<span style="color: #ffffff;">/</span>

<a href="https://drive.google.com/file/d/0B7h3db7B30CedE96N0U2TDlfdEU/view?usp=sharing" target="_blank" rel="noopener noreferrer"></a>

&nbsp;',
	),
	'qr14' => array(
		'title' => 'qr14 - גורילות בערפל האמזונס',
		'html'  => 'פדרו, הילד המקומי, תפס את העניין מהר מאוד!

ככה זה, לפעמים אנחנו עושים דברים גם כשההיגיון והמצפון צועקים לנו לא. לפעמים הבחירות שלנו בחיים לא ממש נכונות, או מושפעות מלחץ חברתי, מבורות או מסתם טמטום. לפעמים אנחנו בוחרים להתעלם מנוּרות אדומות, לפעמים אנחנו משתפים פעולה רק כי נדמה לנו שאין ברירה, ולפעמים זו רק שאלה של גיל. הייתי צעיר, רק השתחררתי מהצבא. הייתי רגיל לציית להוראות ולעשות מה שאומרים לי, בלי לשאול יותר מדי שאלות ובלי לחשוב על ההשלכות.

&nbsp;

תיעוד וידאו נדיר (!!!) שצולם בשנת 1976, כששבט מפפואה-גינאה החדשה פגש לראשונה את האדם הלבן! שני הצדדים מבולבלים, מתקשים מאוד לתקשר. האדם הלבן מושיט יד לשלום "כמקובל", אך הצד השני מגיב בבהלה של ממש, לא מאמינים למראה עיניהם. אדם לבן!!! אל? שד? מפלצת? העיניים של המקומיים מדברות בעד עצמן. מה עובר להם בראש כשמציגים להם גפרורים, ראי, סיר אורז... סרטון נדיר ומרגש:

&nbsp;

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/xd0I1xAICOc" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>ב-2008 שוחרר לרשת צילום וידאו נדיר, שצולם ממטוס, על שבט אבוד באמזונס שמעולם לא בא במגע עם האדם הלבן, ממש כמו שתיאר לנו המדריך. זמן קצר לאחר מכן הסרטון הוסר. חלק טענו שהוא מבוים, חלק טענו שהוא אמתי. חוקר ברזילאי מטעם ממשלת ברזיל יצא ב-2015 לחפש את השבט המתועד בווידאו הזה, במטרה להוכיח שהם קיימים ולהגן עליהם מפני הכחדת היערות (נכון להיום, 70 אחוז מהאמזונס הפרואני כבר נכרת!). הנה סרטון בן 50 דקות שמתאר את המסע של אותו חוקר. מי יודע, אולי יש עוד שבטים אבודים כאלה באמזונס. אני משוכנע שכן! והלוואי שלא יימצאו אותם לעולם!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/sLErPqqCC54" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>גרף המתאר את קצב בירוא יערות האמזונס בברזיל. מפחיד ומאוד מאוד מטריד!

<img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/mongabay_braz_defor_88-05.jpg" alt="" loading="lazy" />',
	),
	'qr15' => array(
		'title' => 'qr15 - היקיקומורי',
		'html'  => 'הכל אודות תופעת ההיקיקומורי ביפן (באנגלית)

מפחיד!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/G7UHX9PsbEc" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>ובנימה אופטימית זו, רגע לפני שהמושג היקיקומורי חוצה את גבולות יפן וחודר גם אל ארצנו ואל חדרי ילדינו, כדאי לזכור כי לעיתים חיבוק זה כל מה שאנחנו צריכים. בעידן הזה של ניכור חברתי טכנולוגי, לרבים מאתנו חסר המגע האנושי הפשוט וכה בסיסי הזה. זה היה בחור אוסטרלי בשם Juan Mann שבשנת 2004 החליט לקום ולעשות מעשה. בווידיאו המצורף מטה ניתן לראות תיעוד של השפעת הקמפיין המדהים שלו מסביב לעולם. קמפיין free hugs שכבר הפך מאז לתנועה של ממש. עשרות מיליונים צפו בסרטון שלו ומאז פרסומו הועלו לרשת עשרות סרטונים דומים מכל רחבי העולם ותמיד עם אותו שיר נושא חזק ומרגש.<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/vr3x_RRJdd4" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr16' => array(
		'title' => 'qr16 - דם על הידיים',
		'html'  => 'בחיאת חברים,

אם צלחתם את הטקסט הלא פשוט הזה וכבר טרחתם לסרוק את הקוד ולהגיע עד לכאן,

בקשה קטנה ממני:

סעו בזהירות.

סעו בכבוד.

בלי לעשות שטויות.

בלי עקיפות מיותרות,

בלי מהירויות מופרזות,

בלי לסמס בזמן הנהיגה.

גם את, דודה יקרה שלי.

גם את!

&nbsp;

אחד הקמפיינים החזקים ברשת: אם נוהגים – לא מסמסים!

&nbsp;

<strong> </strong>

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/R22WNkYKeo8" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>"השיר מדבר על שתי השניות האלה, שכל החיים חולפים מול העיניים. כל המקומות, הזיכרונות, הדרכים, כל התהיות, וברגע כזה כל הטפל נעלם וברור מה חשוב יותר ומה פחות. השיר מדבר על סוג של התעוררות, על אירוע משמעותי שקורה מתישהו לכל אחד בחייו, שאחריו ברור לו איך ולאן הוא ממשיך ועל מה הוא מסכים לוותר. ברגע כזה הכל מתבהר וערך החיים גובר על הכל". <strong>אברהם טל:</strong><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/-zzdy7rITrs" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr17' => array(
		'title' => 'qr17 - יוגי לודג\'',
		'html'  => '<p style="text-align: right;">נועה צפי ואורן שמחות מאוד לראותנו.</p>
<p style="text-align: right;">האמינו לי, אנחנו שמחים הרבה יותר.</p>
<p style="text-align: right;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: right;"></p>
<span style="color: #ffffff;">/</span>

<span style="color: #ffffff;">/</span>
<p style="text-align: right;">שמרו למקרה הצורך. מפת ההגעה ליוגי לודג\' מתחנת הרכבת. שימו לב להערה המצורפת בתחתית המפה!!!</p>
<p style="text-align: right;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: right;"></p>
<p style="text-align: right;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: right;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: right;">וראנסי:<strong> </strong></p>
<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/7vaiO1zytJY" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

סרט מטורף על כת האגורי בהודו, אלה הסאדואים שחיים ליד גתות השריפה וניזונים מהמתים:<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/GEpJdHS1pV0" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>אלבום תמונות מווארנסי. צילום עריכה ומוסיקה מקורית מאולתרת: אסף פולק:<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/fHtIIa4kpDM" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr18' => array(
		'title' => 'qr18 - אחד לשלושה טריליון',
		'html'  => 'אחת מהצעות הנישואין המקוריות והמרגשות ברשת

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/gYh9DCN8ads" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr19' => array(
		'title' => 'qr19 - הפיצה הכי טעימה שאכלתי בחיים',
		'html'  => 'סרטון חזזזק ביותר שזכה בכמה פרסים!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/RpjHSiQLPmA" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>https://www.instagram.com/p/BNc6l1chevh/',
	),
	'qr20' => array(
		'title' => 'qr20 - אבא, אני רעב',
		'html'  => '<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/06hV0Ac_fF4" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr21' => array(
		'title' => 'qr21 - ג\'סי ראם!',
		'html'  => 'שני הודים דקיקים מנסרים לי חתיכה יפיפייה של עץ טיק

<img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4030994475.jpg" alt="" loading="lazy" />

<span style="color: #ffffff;">/</span>

קשה לתאר במילים את הקסם של האיש הזה. מוקש צולל בתוך גזע של דיג\'.<span style="color: #ffffff;">/קשה לתאר במילים את הקסם של האיש הזה. מוקש צולל בתוך גזע של דיג\'.</span>
<p dir="rtl"><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4030995601.jpg" alt="" loading="lazy" /></p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl">שני פאקירים שנחתו במרכז החצר עם נחש קוברה ועשו לנו שמח. 100 רופי מכל אחד בהחלט סיפק אותם.</p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl"><em><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4030994831.jpg" alt="" loading="lazy" /> </em></p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl">ג\'ם ספונטני מסביב למדורה. תכף הצא\'י יהיה מוכן.</p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl"><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4030995255.jpg" alt="" loading="lazy" /></p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl">מחוץ לחצר של מוקש. ההודים רואים מצלמה - ישר רוצים להצטלם! תוך שניות הקיפו אותי עשרות ילדים. נרתיק הדיג\' תלוי לי על הכתף.</p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl"><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4030995031.jpg" alt="" loading="lazy" /></p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<p dir="rtl"><em>"very special didgeridoo..."  </em><em>המזכרת היחידה שנותרו  לי ממנו ומנרתיק ה-ג\'סי ראם הקדוש. </em><strong><em>LET GO!!!</em></strong></p>
<p dir="rtl"><span style="color: #ffffff;">/</span></p>
<img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/flickr_4031748522.jpg" alt="" loading="lazy" />

&nbsp;
<p dir="rtl" style="text-align: center;"><span style="color: #ffffff;">/</span></p>',
	),
	'qr22' => array(
		'title' => 'qr22 - בולט אנט',
		'html'  => '<em>הכל אודות טקס הלוחמים והנמלים הקדושות שרינלדו סיפר לי. לראות ולא להאמין!</em> <em>נשיונל ג\'אוגרפיק.</em>

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/ZGIZ-zUvotM" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><em>והנה</em><em> קטע מערוץ דיסקברי. זווית אחרת על אותו טקס. חופשי אפשר למות מזה. צפו עד הסוף!</em><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/VarqiOM4-Fg" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr23' => array(
		'title' => 'qr23 - יום כן יום לא',
		'html'  => 'הדברים שזוגות עושים בשביל להיכנס להריון:<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/CXMkXS4tSJU" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>העצות שזוגות מקבלים בזמן ההריון:<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/-_gUeNMa3mA" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr24' => array(
		'title' => 'qr24 - קוֹל פּוּט שוֹרט סטופ!',
		'html'  => '<strong>Thrive</strong> הוא סרט דוקומנטרי מיוחד במינו, שמנסה להרים את צעיף האשליה מעל למה שבאמת קורה בעולם דרך חקירה של מסלול הכסף ומי מרוויח ממה שקורה.
הסרט צבר מיליוני צפיות ברחבי העולם, וכעת הוא גם מתורגם לעברית.
בסרט מרואיינים פורצי דרך בתחומים כמו מדע וטכנולוגיה או אנרגיה חופשית, לצד פילוסופים, אנשי רפואה ועיתונאים בתקשורת האלטרנטיבית.
כולם מסכימים שאנחנו חיים בתקופה מדהימה ושחומות המידע, שסגרו על האנושות זמן רב, מתחילות להתפורר.

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/vYzxryWHVZs" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr25' => array(
		'title' => 'qr25 - גרין ווש',
		'html'  => 'במציאות של היום, כבר קשה מאוד לדעת איזה מוצר ירוק ואיזה לא, מי עושה עלינו גרין-ווש ומי דובר אמת. בארה"ב כבר עושים לצרכנים חיים קלים יותר: מוצרים ירוקים באמת, כאלה שלא פוגעים בסביבה, או לפחות לא ביערות האמזונס, מסומנים בסימון מיוחד. תארו לכם מה היה קורה אם בכל העולם היו מסמנים כך את המוצרים, ועוד יותר מזה – אם היו עושים את זה הפוך: במקום לסמן רק מוצרים ירוקים, היו מסמנים מוצרים שחורים. ובגב של כל מוצר שחור כזה היתה מופיעה רשימה במי המוצר הזה פוגע ולמי הוא מזיק ואילו חיות נכחדו בגללו, וכמה עצים נכרתים מדי יום כדי להמשיך לייצר אותו... אין ספק, סימון כזה היה עושה פה מהפכה אמיתית.

&nbsp;

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/3iIkOi3srLo" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr26' => array(
		'title' => 'qr26 - כורסת הציפורניים',
		'html'  => 'כך בדיוק נראתה הלידה שלנו.

בול!!!

רק שאצלנו היו גם שלושה דולפינים וארבעה פינגווינים ;-)

&nbsp;

<strong> </strong><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/oCxtOE_1pr0" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr27' => array(
		'title' => 'qr27 - אמסטרדם',
		'html'  => 'גאונים.

מאסטרים.

ביל היקס ו-לואיס סי.קיי

בשני קטעים קורעים שכבר מזמן נכנסו לפנתיאון!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/UMXfUbRuoSU" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>לואיס סי. קיי.<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/8yEgJ-xeoXQ" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr28' => array(
		'title' => 'qr28 - נזכור ולא נשכח',
		'html'  => 'הרגלי אכילה מסביב לעולם. פרויקט מיוחד משנת 2005 שחקר 30 משפחות ב-24 מדינות. <strong><a href="http://www.fubiz.net/2013/05/07/what-the-world-eats/">צפו באלבום המלא והמרתק כאן&gt;&gt;</a></strong>

&nbsp;

<a href="http://www.fubiz.net/2013/05/07/what-the-world-eats/"><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/eat2-450x297.jpg" alt="" loading="lazy" /></a> <strong>VS.</strong> <img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/eat1-450x297.jpg" alt="" loading="lazy" />

&nbsp;

מה אוכלים לארוחת בוקר מסביב לעולם?<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/ry1E1uzPSU0" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>סדרה מרתקת של הנשיונל ג\'אוגרפיק בת 10 פרקים על "טביעת רגל אקולוגית":<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/VcxQjGPDKHE" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr29' => array(
		'title' => 'qr29 - לעבור דירה',
		'html'  => '<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/OUh8_Yz-cXg" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr30' => array(
		'title' => 'qr30 - פרדס חפלה',
		'html'  => 'לפרדס חנה יש כבר שני המנונים.

אחד של אהוד והשני של אברהם.<span style="color: #ffffff;">/</span><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/kCR7tO3WoIQ" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/ffN6QnPohv8" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>ואם כבר בהמנונים וסמלים עסקינן.. קבלו את הסמל הבלתי רשמי של הפרדס.

כיכר חמור התפוזים באדיבות המועצה המשעשעת שלנו.

חמור שעבר שדרוג קטן...

מחווה למועדון היוניקורן החדש.

מעתה אמרו כיכר החמוריקון ;-)

&nbsp;



&nbsp;

טוב נו, לא הצלחתי להתאפק.. אם כבר מדברים על פרדס חנה...

איך אפשר בלי קטע קטן מהסיפור על המקום המיוחד הזה.

סיפור שתמיד עושה שמח!

צולם בהופעה בתיאטרון הידית כמה ימים אחרי שהסיפור הזה נכתב.<p class="ea-qr-embed ea-qr-embed--link"><a href="https://www.facebook.com/eyal.amit.show/videos/799116743508383/" target="_blank" rel="noopener noreferrer">צפייה בסרטון ↗</a></p>',
	),
	'qr31' => array(
		'title' => 'qr31 - פיפי במעלית',
		'html'  => 'קוסטה ריקה – גן עדן עלי אדמות

ולא רק למטיילים,

גם לגולשים!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/8nJc-vQFeow" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>הנה עוד אחד שיעשה לכם חשק לעזוב הכל ולקנות כרטיס!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/B57UTkxCjPY" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>ואיך אפשר בלי תמונה אחת שלנו.. עם אביב על הגב בחוף מנואל אנטוניו ;-)

&nbsp;',
	),
	'qr32' => array(
		'title' => 'qr32 - נשימה מעגלית',
		'html'  => '<div>ברוכים הבאים למרכז לטיפול בנשימה באמצעות דיג׳רידו בפרדס חנה - המקום שבו אני חי, נושם, מלמד, בונה ומטפל באמצעות כלי הדיג\'רידו.</div>
<div>אם מתעוררת בכם הקריאה ללמוד לנגן בכלי הדיג\'רידו הייחודי והקדום הזה, אם ניסיתם בעבר ולא הצלחתם, אם הייתם רוצים לדעת לנשום נכון, להפחית מתח (סטרס) בחיים, למצוא את השקט והשלווה, להתוודע עם איכויות הריפוי העמוקות של הדידג\'רידו, לבנות לעצמכם דידג\'רידו מקצועי , לתקן כלי סדוק וישן, לרכוש כלי חדש, או לקבל טיפול סאונד הילינג עוצמתי בשיטה ייחודית .שפיתחתי, אני כאן, באהבה כה גדולה, עם 21 שנות ניסיון בנגינה, בהוראה, בבניית כלי הדידג\'רידו ובטיפול באמצעותו</div>
<div></div>
<div>עם סבלנות אין קץ, חיוך גדול ותחושת שליחות אמיתית, אשמח מאוד לפגוש גם אתכם.</div>
<div>מוזמנים לצפות בוידאו המצורף כאן למטה (7 דקות) שלוקח אתכם לסיור קטן בסטודיו</div>
<div></div>
<div><strong>לפרטים נוספים מוזמנים ליצור קשר</strong> <strong>052-4822842</strong></div>
<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/wDQoJauqsRM" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>אוגוסט 2004, 38 מעלות בצל, 90 אחוזי לחות, 300 איש על גג מסעדת הטאלי 24 רופי ברחוב שוקן בתל אביב. השקת הספר השני שלי - כושי בלאנטיס. יורם סיוון, טל אפריים ואנוכי בתעופות. הערב המדהים הזה ילווה אותי כל חיי. לשים אזניות, להגביר את הווליום ולעוף!

זמן חלום.<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/6DzgrvZf1tg" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>יואב קליינמן המלך. מומחה לפתיחת צ\'אקרת הדיג\'. תודה חבר יקר!
<div class="mceTemp"> /</div>


/

אדם הניוזילנדי מטיס אותי לחלל החיצון. רואים לא? יא אללה, איך אני עף!!! :-)



/

יורם סיוון ויאיר גפני – (בראשית 2004). יאיר כבר בלי הראסטות.



/

מוקש ואני בשנת 2000. תמיד תהיתי לגבי התמונה הזו.

קרן האור המכושפת הזאת שיוצאת לו מהמצח…



/

הפסקת ניגון בחצר של מוקש. שנת 2000.

הצ\'אי כבר על האש. ה-דיג\'ים בפול פאואר!!!



/

let go !!! אבל עם חיוך :-) דיג\' הספירלה המטורף שבניתי אצל מוקש



&nbsp;

המרכז לטיפול בדיג\'רידו  פרדס חנה. היום.

<img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/378172116_789649869834098_921032953608050382_n-450x448.jpg" alt="המרכז לטיפול בנשימה באמצעות דיג\'רידו פרדס חנה אייל עמית" loading="lazy" />

<a href="https://www.facebook.com/didgeridoo.studio.eyal.amit" target="_blank" rel="noopener noreferrer">לדף הפייסבוק שלנו</a>
<h5>תמונות נוספות מהמרכז לטיפול בנשימה באמצעות דיג\'רידו פרדס חנה.</h5>
<h5>שיעורי נגינה בדידג\'רידו, סדנאות בנייה דידג\'רידו וטיפולי נשימה וסאונד הילינג בדידג\'רידו:</h5>',
	),
	'qr33' => array(
		'title' => 'qr33 - תאכלו ביצים, תהיו טייסים',
		'html'  => '<a href="http://enchroma.com/test/instructions/"><img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/color-1024x437.jpg" alt="color" loading="lazy" /></a>אז זהו, מתברר שעוורון צבעים ניתן כיום לתיקון פשוט בעזרת משקפיים עם עדשות מיוחדות של חברת enchroma. יוטיוב מפוצץ בסרטונים של עיוורי צבעים שקנו את המשקפיים האלה והרכיבו אותם לראשונה. התגובות מטורפות!

לפני שאתם רצים לקנות משקפיים כאלה, עשו קודם את המבחן באתר שלהם (50 שאלות) ואז תדעו בדיוק איזה סוג של עוורון צבעים יש לכם ואילו עדשות יכולות לתקן את זה. יש להם כל מיני דגמים, לבחוץ, לבפנים, לעבודה מול מחשב, וגם כמה דגמים מגניבים לילדים. שווה לאללה!

<strong><a href="http://enchroma.com/">הנה הקישור לאתר&gt;&gt;</a></strong>

<strong><a href="http://enchroma.com/test/instructions/">הנה הקישור למבחן&gt;&gt;</a></strong>

אוקיי, אז הטכנולוגיה היום כבר מצליחה לתקן את העניין ומאפשרת לעוורי צבעים לראות לראשונה בחייהם איך באמת נראה הצבע הסגול.. או כל צבע אחר.

את העניין הזה סגרנו. אבל עכשיו שאלה אחרת תקועה לי חזק בראש:

האם הטכנולוגיה תאפשר לכולנו יום אחד לראות גם את אלוהים?

תתפלאו, יש לא מעט מדענים שבטוחים שכן.

ואתם?

התגובה המרגשת של עיוורי צבעים בפעם הראשונה שלהם עם משקפי encroma. מהפכה!!!!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/V9nYSJLwXEI" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr34' => array(
		'title' => 'qr34 - תקום',
		'html'  => 'אין ספק, אם יש דבר אחד בהורות שיכול להביא את הזוג אל הקצה, שיכול לדחוף את שניהם אל סף שיגעון וטירוף..

זו ללא ספק העייפות המצטברת מתינוק בוכה שלא נותן לישון בלילה.

אבל באותה קלות שתינוקות יכולים להביא אותנו לקצה, הם יכולים גם להפגיש אותנו עם רגעי אושר שקשה מאוד להביע במלים.

חשבתם על זה פעם, הנשים הן אלה שנכנסות להריון, נושאות את העובר תשעה חודשים ארוכים. בחילות, בדיקות, כאבי גב... ואז הלידה המטורפת הזאת, ואז התינוק בא הביתה, ואז הן מטפלות בו, ומניקות אותו, ומחתלות אותו ודואגות לו... ואחרי כל הטירוף ושיגעון הזה, מה המלה הראשונה שהילד אומר?

נכון מאוד,

"אבא!"

:-)

<span style="color: #ffffff;">/</span>

קבלו את אביב, הבת הבכורה שלנו. כאן בווידאו בת שנה ושלושה חודשים. עוד לא הולכת, אבל כבר מדברת. וכן, גם אצלנו המלה הראשונה היתה "אבא",

רק שאצלנו זו היתה גם המלה היחידה ;-)<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/VRnBeF2DS74" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr35' => array(
		'title' => 'qr35 - הגבר החדש',
		'html'  => 'וכן.. בפעם הבאה אולי באמת כדאי שתשתמש בקונדום! ;-)<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/LyhapayOx44" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
<h3><strong><u>אבולוציה אימהית (רץ ברשת)</u></strong></h3>
<strong>(בגדי הריון):</strong>

ילד ראשון – את מתחילה ללבוש בגדי הריון מיד כשאת מקבלת אישור שאת בהריון.

ילד שני – את לובשת את בגדייך הרגילים עד כמה שאת יכולה.

ילד שלישי – בגדי ההריון שלך הם הבגדים הרגילים שלך.

&nbsp;

<strong>(הכנה ללידה):</strong>

ילד ראשון – את מתרגלת נשימות באדיקות.

ילד שני – את לא טורחת לתרגל כי את זוכרת שבפעם שעברה, הנשימות לא עזרו בכלל.

ילד שלישי – את מבקשת אפידורל בחודש השמיני.

&nbsp;

<strong>(בגדי התינוק):</strong>

ילד ראשון – את מכבסת את בגדי התינוק הנולד, מפרידה צבעים, מקפלת בצורה מסודרת ומניחה בתוך השידה.

ילד שני – את בודקת שהבגדים נקיים ומשליכה רק את אלה עם הכתמים הכהים.

ילד שלישי – גם בנים יכולים ללבוש ורוד, לא?

&nbsp;

<strong>(דאגות):</strong>

ילד ראשון – בסימן המצוקה הראשון, ילָלה או מבט זועף, את מרימה את התינוק על הידיים.

ילד שני – את מרימה את התינוק כשהיללות שלו מאיימות להעיר את הילד הראשון.

ילד שלישי – את מלמדת את הילד הראשון איך להפעיל לתינוק את הנדנדה.

&nbsp;

<strong>(מוצץ):</strong>

ילד ראשון – אם המוצץ נופל על הרצפה, את מרחיקה אותו מהתינוק עד שתגיעי הביתה, תשטפי ותרתיחי אותו.

ילד שני – כשהמוצץ נופל על הרצפה, את שוטפת אותו עם קצת מיץ מהבקבוק של התינוק.

ילד שלישי – את מנגבת ת\'מוצץ בחולצתך ומכניסה אותו בחזרה למקום.

&nbsp;

<strong>(החתלה):</strong>

ילד ראשון – את מחליפה לו חיתול כל שעה, בין אם הדבר נחוץ או לא.

ילד שני – את מחליפה לו חיתול כל שעתיים-שלוש, אם ממש צריך.

ילד שלישי – את משתדלת להחליף לו חיתול רק לפני שאחרים יתחילו להתלונן על הריח.

&nbsp;

<strong>(פעילות):</strong>

ילד ראשון – את לוקחת את העולל לג\'ימבורי, לשיעורי שחייה ולשעת סיפור.

ילד שני – את לוקחת אותו לג\'ימבורי.

ילד שלישי – את לוקחת אותו לסופרמרקט ולניקוי יבש.

&nbsp;

<strong>(יציאה לבילוי):</strong>

ילד ראשון – בפעם הראשונה שאת משאירה את התינוק עם שמרטפית, את מתקשרת הביתה 5 פעמים.

ילד שני – כשאת כבר עומדת בדלת בדרך החוצה, את נזכרת להשאיר מספר טלפון שבו ניתן להשיגך.

ילד שלישי – את משאירה הוראה לשמרטפית לצלצל אלייך רק אם היא רואה דם.

&nbsp;

<strong>(בבית):</strong>

ילד ראשון – את מקדישה נתח נכבד מזמנך להתבוננות ולהתפעלות מהתינוק.

ילד שני – את מקדישה זמן כל יום להתבוננות מחשש שהילד הראשון ימחץ וידחף את התינוק או ירביץ לו.

ילד שלישי – את מקדישה קצת זמן בכל יום להסתתרות מהילדים.

&nbsp;

<strong>(בליעת מטבעות):</strong>

ילד ראשון – כשהילד הראשון בולע מטבע, את ממהרת עם הילד לבית החולים ודורשת צילום רנטגן.

ילד שני – כשהילד השני בולע מטבע, את עוקבת בזהירות עד שהמטבע יוצא מהגוף.

ילד שלישי – כשהילד השלישי בולע מטבע, את מנכה אותו מדמי הכיס שלו.',
	),
	'qr36' => array(
		'title' => 'qr36 - חוני המעגל',
		'html'  => '<strong>כוחה של אמונה</strong>

והפעם, מישהו שהשתמש בכוח הזה למשהו חיובי, על-אנושי ממש!

קליפ שכולו השראה

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/qX9FSZJu448" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr37' => array(
		'title' => 'qr37 - דרך השלום',
		'html'  => 'מגזין \'טיים-אאוט\' בפרוייקט מיוחד!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/N8DMGaeDXE4" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>כולם רוצים שלום.

ברור, ברור.

אבל הנה כמה סיבות טובות למה אסור שזה יקרה אף פעם!!!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/uvq0iCVGih0" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr38' => array(
		'title' => 'qr38 - הבטחות או לא להיות',
		'html'  => 'לא נעים להיתקע במעלית.

"לא נעים" אפילו לא מתקרב למה שעבר על האיש האומלל הזה.

41 שעות של ייסוריי קלסטרופוביה

אלוהים יודע מה עבר לו בראש בזמן הזה

אמיתי לגמרי!

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/p_bMhNI_TY8" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr39' => array(
		'title' => 'qr39 - תחשוב חיובי',
		'html'  => '<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/s5nWjY4aHos" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr40' => array(
		'title' => 'qr40 - אבנים חמות',
		'html'  => 'אחרי 1,941 ימים בשבי החמאס שבהם מדינה שלמה התפללה לשובו, ובחלוף שנה מאז שחרורו,

גלעד שליט בראיון מיוחד:

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/aOx_-iyEDgA" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr41' => array(
		'title' => 'qr41 - לופ בטעם תות לימון',
		'html'  => 'בברמיצווש שלי

פרשת שמות

6:50 בבוקר

תכף יזרקו סוכריות

&nbsp;',
	),
	'qr42' => array(
		'title' => 'qr42 - הבטחות אחים',
		'html'  => 'אין, אין לתאר כמה שמחה ואושר כלב מכניס הביתה.

אם גם הילדים שלכם יושבים לכם עכשיו על הווריד, ואתם משוכנעים באלף אחוז שכל הטיפול בו יהיה בסופו של דבר עליכם (אתם לגמרי צודקים)...

האמינו לי, זה שווה את זה!

אין יצור בעולם הזה שיאהב אתכם כמו כלב. אין!

תמיד, וכל הזמן, ולנצח!

בלי אולי ובלי אבל ולא רק כשמתחשק לו.

הוא יאהב אתכם תמיד.

כלב שמטפלים בו יפה ונותנים לו אהבה מכיר רק רגש אחד,

אהבה!

אז..

אם כבר החלטתם להביא כלב הביתה, עזבו אתכם מהגיזעיים והמפונפנים עם תעודות והקבלות .

מי צריך את התעודות האלה בכלל?

אמצו כלב מתוק ומקסים שמקשקש בזנב ומלקלק עם הלשון ומחייך עם העיניים.

לא חסרים עמותות שרק מתחננות שנבוא ונציל את הכלבים האומללים האלה.

והאמינו לי, כלב שמצילים אותו, יודע וזוכר את זה כל חייו. לא תדעו אהבה כזו לעולם.

&nbsp;

בשדות מאחורי הבית, שוקו ואביב בתעופות. תרתי משמע!

&nbsp;

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/b0KuMrWlj80" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>נו יאללה, אז אתם מאמצים היום כלב?

<img class="ea-qr-img" src="/wp-content/uploads/ea-legacy/qr/IMG_7784-1024x943.jpg" alt="אייל עמית" loading="lazy" />',
	),
	'qr43' => array(
		'title' => 'qr43 - עכשיו!!!',
		'html'  => '<strong>הודים מטוגנים מעל הסירים</strong>

אוכל-רחוב בהודו שיפתח לכם את התיאבון

ע-כ-ש-י-ו !!!!!!!!!!!!!!!!!!!!

;-)

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/O5-p5R-Uk0c" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr44' => array(
		'title' => 'qr44 - כולנו פרעושים',
		'html'  => '<p style="text-align: right;">ללא ספק, מבין כל ההרצאות ששמעתי בחיי, זוהי ההרצאה הכי חשובה.</p>
<p style="text-align: right;">הרצאה של 70 דקות.</p>
<p style="text-align: right;">מלא-מלא זמן, אני יודע!</p>
<p style="text-align: right;">אם מישהו היה מבקש ממני לצפות בהרצאה של שעה ועשר דקות, הייתי צוחק לו בפרצוף.</p>
<p style="text-align: right;">למי יש היום את הזמן הזה – שעה ועשר דקות!?!</p>
<p style="text-align: right;">אבל...</p>
<p style="text-align: right;">אם אספר לכם שזאת אולי ההרצאה הכי חזקה, הכי מדהימה, הכי מרתקת, הכי מטלטלת, הכי אקזוטית (אתם עוד לא מבינים כמה אקזוטית!) שתשמעו בחיים שלכם – תאמינו לי?</p>
<p style="text-align: right;">זו ההרצאה שהפכה לי את החיים ואני מקווה מאוד שהיא תהפוך גם את שלכם, בלי שתצטרכו להיות גיבורים "אמיתיים" בעתיד.</p>
<p style="text-align: right;">אני מבטיח לכם, הסרט הזה יעבור לכם מהר. הוא חזק, הוא מזוקק. פַּנו לעצמכם איזה ערב, בלי הילדים על הראש, וצפו בהרצאה החשובה הזו. אחר כך תחליטו מה אתם עושים עם המידע הזה.</p>
<p style="text-align: right;">אין לי פה שום מניע נסתר. אני לא מקבל כסף מאיש. אין לי שום קשר לאיש שבסרט. עד שלא צפיתי בהרצאה שלו, אפילו לא שמעתי עליו.</p>
<p style="text-align: right;">תתכוננו, אתם הולכים לפגוש אחד מהאנשים הכי מדהימים על הפלנטה.</p>
<p style="text-align: right;">וזכרו תמיד, לאורך כל הסרט, את משפטו של ה\'זקן\': "כל זמן שאדם חי, הוא יכול להשתנות" – דוד בן-גוריון.</p>

<h3><strong>שימו לב!!! הסרט מכיל כמה מראות קשים והוא אינו מומלץ לצפייה לילדים! </strong></h3>
<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/omweihtaYwI" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr45' => array(
		'title' => 'qr45 - צום מיצים',
		'html'  => 'שי שטרן פוגש את כוהנת הסופר-פודס <a href="https://www.facebook.com/UminaSuperfood/" target="_blank" rel="noopener noreferrer"><strong>אומינה קדמי</strong></a> ובודק מהי התזונה הכי בריאה?

<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/3o6vI1EHlOU" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr46' => array(
		'title' => 'qr46  - האומץ לאהוב את הפחד',
		'html'  => '<h3 style="text-align: center;"><span style="color: #ff0000;">"לעולם לא תוכל לחצות את האוקיינוס עד שיהיה לך האומץ לאבד את מראה החוף"</span></h3>
<p style="text-align: center;"><strong>-כריסטופר קולומבוס-</strong></p>
<p style="text-align: center;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: center;"><span style="color: #ffffff;">/</span></p>
<p style="text-align: center;">ואם בנושא ה"פחד" עסקינן,</p>
<p style="text-align: center;">איך אפשר בלי הציטוט המפורסם ומלא ההשראה של <a href="https://greenbrothers.co.il/search?type=product&amp;q=%D7%9E%D7%A8%D7%99%D7%90%D7%9F%20%D7%95%D7%99%D7%9C%D7%99%D7%90%D7%9E%D7%A1%D7%95%D7%9F" target="_blank" rel="noopener noreferrer">מריאן ויליאמסון</a></p>
<p style="text-align: center;">מתוך "בחזרה לאהבה: הרהורים על עקרונות הקורס בניסים" (אור עם, 1993<em>)</em></p>
<p style="text-align: center;">לגזור ולשמור</p>
<p style="text-align: center;">לשנן ולהפנים:</p>

<h3 style="text-align: center;"><span style="color: #ff0000;"><em>"הפחד העמוק ביותר שלנו הוא לא שמא אנחנו חלשים מדי. הפחד העמוק ביותר שלנו הוא שאנחנו בעלי עוצמה שמעל לכל שיעור. זה האור שבנו, לא האפלה שבתוכנו, שמפחיד אותנו יותר מכל. אנחנו שואלים את עצמנו – איזו זכות יש לי להיות מבריק, יפהפה, מוכשר ואהוב? למען האמת, איזו זכות יש לכם לא להיות? אתם ילדיו של אלוהים. כשאתם בוחרים לשחק בקטן אתם לא משרתים את העולם. אין שום דבר נאור בצמצום האישיות שלנו כדי שאחרים לא ירגישו חסרי ביטחון. נולדנו כדי לממש את הקסם האלוהי הגלום בנו. הוא לא גלום רק בחלק מאיתנו, כל אחד מאיתנו נושא את הקסם הזה בתוכו. כאשר אנחנו נותנים לאור הפנימי שלנו לזרוח אנחנו מעניקים, בלא מודע, רשות לאחרים לעשות כמונו. כשאנחנו משתחררים מהפחדים שלנו, הנוכחות שלנו משחררת אחרים."</em></span></h3>
<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/0CPJ-AbCsT8" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
	),
	'qr47' => array(
		'title' => 'qr47  - טיפול זוגי',
		'html'  => 'ודרך אגב, רק שתדעו שאני בכלל לא נוחר.

ממש לא!

ענת סתם אומרת

אל תאמינו לה.

וכן, אני עדיין מחכה שהיא תסגור את הדלת של המקרר, ותכבה את האורות ותחסוך קצת בטישואים,

חחח... אני יודע שזה לא יקרה בחיים.

אבל איך אומרים, שאלה יהיו הצרות שלנו.

ואני לא נוחר.

אני לא נוחר, נו!

זאת בכלל ענת שנוחרת!

הנה תראו,

וידאו קורע מצחוק. פיפי בתחתונים!!!<div class="ea-qr-embed ea-qr-embed--video"><iframe src="https://www.youtube-nocookie.com/embed/CzLGk0VezzQ" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>סתאאאאם..

ברור שזו לא ענת.

והיא גם לא נוחרת.

אבל תודו, זה היה יכול להיות מאוד משעשע אם כן ;-)

ותרגעו, עוד לא נגמר.

עמוד 253 - <strong>וסיימתָ</strong>

נתראה שם ;-)

&nbsp;',
	),
	'qr48' => array(
		'title' => 'qr48 -וסיימת',
		'html'  => '<div></div>
<div style="text-align: right;">אם הגעתם לכאן סימן שסיימתם את הספר, או שאתם מאלה שלא יכולים להתאפק וישר קופצים לראות מה קורה בסוף. זה בסדר, תרגישו חופשי, גם אני כזה ;-)</div>
<div style="text-align: right;"></div>
<div style="text-align: right;">מעומק הלב, אני רוצה להגיד תודה שהקדשתם מזמנכם לקריאת הספר הזה.</div>
<div style="text-align: right;">רוצה לשתף אתכם שאני עם עצמי עברתי מסע לא קטן בזמן כתיבתו, עריכתו ויציאתו לאור. וואוו, חשבתי שבספר השלישי זה כבר יהיה הרבה יותר קל.</div>
<div style="text-align: right;">ממש ממש לא.</div>
<div style="text-align: right;">בדיוק להפך!</div>
<div style="text-align: right;">התערבלתי לא מעט עם עצמי עד שהוא ראה אור. 3.5 שנים ליתר דיוק!</div>
<div style="text-align: right;">חלק מהסיפורים בו לא פשוטים, אני יודע. חלקם גם מאוד אישיים וחושפניים ונדרשתי לגייס את מקסימום האומץ וההעזה שלי כדי להוציא אותם לאור.</div>
<div style="text-align: right;"></div>
<div style="text-align: right;">כמו החיים, כך גם הסיפורים: מצחיקים, עצובים, מרגשים, מטלטלים, מכעיסים, מעודדים..  קשת רחבה של רגשות העשויים להתעורר במהלך קריאתו.</div>
<div style="text-align: right;"></div>
<div style="text-align: right;">אם רכבת ההרים הריגשית הזאת הצליחה באיזשהו מקום לגעת בכם, אם יש משהו שהייתם רוצים לשתף, לספר, לשאול, לצעוק, ללחוש, לבקש, להציע או סתם לשחרר משהו שמבקש לצאת עכשיו החוצה.. אני מזמין אתכם באהבה רבה לשתף הדברים פה בתגובות למטה או הודעה בפרטי. אשמח לשמוע מכם. ובכלל, אשמח לפגוש ולהכיר אתכם גם בערוצים נוספים שלי:</div>
<div style="text-align: left;">    <a href="/%D7%9E%D7%95%D7%96%D7%94-%D7%94%D7%95%D7%A6%D7%90%D7%94-%D7%9C%D7%90%D7%95%D7%A8/" target="_blank" rel="noopener noreferrer">ספרים&gt;&gt;</a>            <a href="/blog/" target="_blank" rel="noopener noreferrer">בלוג &gt;&gt;</a>           <a href="/%D7%AA%D7%95%D7%A4%D7%A2%D7%AA-%D7%99%D7%97%D7%99%D7%93/" target="_blank" rel="noopener noreferrer">מופע הסיפורים&gt;&gt;</a></div>
<div style="text-align: left;"></div>
<div style="text-align: left;"><span style="color: #ffffff;"> /האומץ</span></div>
<div style="text-align: left;">האומץ לאהוב את הפחד</div>
<div style="text-align: left;">וכתבת וסיפרת</div>
<div style="text-align: left;">באהבה ותודה</div>
<div style="text-align: left;">אייל</div>
<div style="text-align: right;"></div>',
	),
);
