<?php
/**
 * Plugin Name: EA W2-09 — Legacy 301/410 map (generated)
 * Description: GENERATED by scripts/gen_htaccess_301_from_decisions.py from
 *   hub/data/decisions/redirects-301-eyal-final-2026-05-27.json (135 decisions, approach B).
 *   DO NOT hand-edit. .htaccess is inert on this stack (nginx); PHP is the live mechanism.
 * Version: 1.0.0
 */
defined( 'ABSPATH' ) || exit;

function ea_w209_legacy_redirects() {
	if ( is_admin() || wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) { return; }
	$uri = isset( $_SERVER['REQUEST_URI'] ) ? rawurldecode( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '';
	if ( $uri === '' ) { return; }
	$path = (string) wp_parse_url( $uri, PHP_URL_PATH );
	if ( $path === '' ) { return; }
	$norm = trailingslashit( $path );

	// 410 Gone
	$gone = array(
		'/qr/פרק-א/',
		'/thankyou/',
	);
	if ( in_array( $norm, $gone, true ) ) {
		status_header( 410 ); header( 'X-EA-Redirect: w209-410' ); nocache_headers();
		exit;
	}

	// W2-06 blog migration: legacy /Blog/<slug> (capital B) -> /blog/<slug> (regex prefix;
	// the exact-match $map below cannot express a prefix). Lowercase /blog/ won't match -> no loop.
	if ( preg_match( '#^/Blog/(.+)$#', $path, $m ) ) {
		header( 'X-EA-Redirect: w209-blog' );
		wp_redirect( home_url( '/blog/' . $m[1] ), 301 );
		exit;
	}

	// 301 legacy -> new
	$map = array(
		'/צור-קשר/' => '/contact/',
		'/כתבות-בתקשורת-אודות-מופע-הסיפורים-של-א/' => '/shows/',
		'/תגובות-גולשים-אודות-״מופע-הסיפורים-של/' => '/shows/',
		'/מוזה-הוצאה-לאור/וכתבת-אוטוביוגרפיה-בסיפורים/' => '/books/vekatavta/',
		'/הופעות/' => '/shows/',
		'/מוזה-הוצאה-לאור/' => '/books/',
		'/בלוג-דיגרידו-המרכז-לטיפול-בדיגרידו-א/' => '/blog/',
		'/מוזה-הוצאה-לאור/כושי-בלאנטיס-אוטוביוגרפיה-בסיפורים/' => '/books/kushi-blantis/',
		'/והודית/' => '/shows/',
		'/מפת-אתר-site-map/' => '/sitemap_index.xml',
		'/מוזה-הוצאה-לאור/דף-מבצעים-הספרים-של-אייל-עמית-רכישה-יש/' => '/books/',
		'/shop/תקנון/' => '/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/שיעורי-נגינה-בדיגרידו/' => '/lessons/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סדנאות-בנייה-עצמית-דיגרידו/' => '/lessons/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/טיפולי-סאונד-הילינג-דיגרידו/' => '/sound-healing/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/תיקון-דיגרידו/' => '/repair/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/תיקים-לדיגרידו/' => '/bags/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/דיגרידו-למכירה-כלים-בעבודת-יד/' => '/didgeridoos/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סאונד-הילינג-דיגרידו-מדיטציית-דיגריד/' => '/sound-healing/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/הדיגרידו-ככלי-לריפוי-עצמי/' => '/treatment/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/מוקש-דהימן-מאסטר-דיגרידו-דף-להנצחת-זכ/' => '/eyal-amit/mokesh-dahiman/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סטנד-רצפתי-לדיגרידו-לנגינה-בישיבה-נמו/' => '/stand-floor/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סטנדים-לאחסון-דיגרידו-בתלייה-או-בעמיד/' => '/stands-storage/',
		'/וכתבת-אייל-עמית/' => '/books/vekatavta/',
		// WP-CANON T6 — merged from inc/wave2-w2-02.php (canonical /eyal-amit/, single hop).
		'/אייל-עמית-אודות/' => '/eyal-amit/',
		'/about/' => '/eyal-amit/',
		'/about/moksha/' => '/eyal-amit/mokesh-dahiman/',
		'/mokesh-dahiman/' => '/eyal-amit/mokesh-dahiman/',
		'/mokesh/' => '/eyal-amit/mokesh-dahiman/',
		'/shop/cart/' => '/shop/',
		'/shop/checkout/' => '/shop/',
		'/shop/my-account/' => '/shop/',
	);
	if ( isset( $map[ $norm ] ) ) {
		header( 'X-EA-Redirect: w209-301' );
		wp_redirect( home_url( $map[ $norm ] ), 301 );
		exit;
	}
}
// priority 0: run before the site-tree canonical table (priority 1).
add_action( 'template_redirect', 'ea_w209_legacy_redirects', 0 );
