<?php
/**
 * Plugin Name: EA W2-09 — Legacy 301/410 map (generated)
 * Description: GENERATED by scripts/gen_htaccess_301_from_decisions.py from
 *   hub/data/decisions/redirects-301-eyal-final-2026-05-27.json (135 decisions, approach B).
 *   DO NOT hand-edit. .htaccess is inert on this stack (nginx); PHP is the live mechanism.
 * Version: 1.0.0
 */
defined( 'ABSPATH' ) || exit;

function ea_w209_legacy_redirects() {
	if ( is_admin() || wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) { return; }
	$uri = isset( $_SERVER['REQUEST_URI'] ) ? rawurldecode( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '';
	if ( $uri === '' ) { return; }
	$path = (string) wp_parse_url( $uri, PHP_URL_PATH );
	if ( $path === '' ) { return; }
	$norm = trailingslashit( $path );

	// 410 Gone
	$gone = array(
		'/qr/פרק-א/',
		'/thankyou/',
		'/סיני-יוני-09-154/',
		'/סיני-יוני-09-151/',
		'/adi/',
		'/גבי-2/',
		'/רני/',
		'/רני-2/',
		'/איל-מישה-איטליה-כושי-בלאנטיס-1/',
		'/איל-מישה-איטליה-כושי-בלאנטיס-3/',
		'/איל-מישה-איטליה-כושי-בלאנטיס-4/',
		'/שלושת-הספרים-אלקטרוני2/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/studio-bunner/',
	);
	if ( in_array( $norm, $gone, true ) ) {
		status_header( 410 ); header( 'X-EA-Redirect: w209-410' ); nocache_headers();
		exit;
	}

	// 301 legacy -> new
	$map = array(
		'/צור-קשר/' => '/contact/',
		'/כתבות-בתקשורת-אודות-מופע-הסיפורים-של-א/' => '/shows/',
		'/תגובות-גולשים-אודות-״מופע-הסיפורים-של/' => '/shows/',
		'/מוזה-הוצאה-לאור/וכתבת-אוטוביוגרפיה-בסיפורים/' => '/books/vekatavta/',
		'/הופעות/' => '/shows/',
		'/מוזה-הוצאה-לאור/' => '/books/',
		'/בלוג-דיגרידו-המרכז-לטיפול-בדיגרידו-א/' => '/blog/',
		'/מוזה-הוצאה-לאור/כושי-בלאנטיס-אוטוביוגרפיה-בסיפורים/' => '/books/kushi-blantis/',
		'/והודית/' => '/shows/',
		'/מפת-אתר-site-map/' => '/sitemap_index.xml',
		'/מוזה-הוצאה-לאור/דף-מבצעים-הספרים-של-אייל-עמית-רכישה-יש/' => '/books/',
		'/shop/תקנון/' => '/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/שיעורי-נגינה-בדיגרידו/' => '/lessons/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סדנאות-בנייה-עצמית-דיגרידו/' => '/lessons/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/טיפולי-סאונד-הילינג-דיגרידו/' => '/sound-healing/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/תיקון-דיגרידו/' => '/repair/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/תיקים-לדיגרידו/' => '/bags/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/דיגרידו-למכירה-כלים-בעבודת-יד/' => '/didgeridoos/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סאונד-הילינג-דיגרידו-מדיטציית-דיגריד/' => '/sound-healing/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/הדיגרידו-ככלי-לריפוי-עצמי/' => '/treatment/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/מוקש-דהימן-מאסטר-דיגרידו-דף-להנצחת-זכ/' => '/eyal-amit/mokesh-dahiman/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סטנד-רצפתי-לדיגרידו-לנגינה-בישיבה-נמו/' => '/stand-floor/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סטנדים-לאחסון-דיגרידו-בתלייה-או-בעמיד/' => '/stands-storage/',
		'/וכתבת-אייל-עמית/' => '/books/vekatavta/',
		'/אייל-עמית-אודות/' => '/about/',
		'/דיגרידו-סטודיו-נשימה-מעגלית-אייל-עמית-2/דיגרידו-למכירה/' => '/didgeridoos/',
		'/דיגרידו-סטודיו-נשימה-מעגלית-אייל-עמית-2/סדנאות-בנייה-עצמית-דיגרידו/' => '/lessons/',
		'/דיגרידו-סטודיו-נשימה-מעגלית-אייל-עמית-2/תיקון-דיגרידו/' => '/repair/',
		'/דיגרידו-סטודיו-נשימה-מעגלית-אייל-עמית-2/תיקים-וסטנדים-לדיגרידו/' => '/bags/',
		'/פרדס-חנה/הדיגרידו-ככלי-לריפוי-עצמי/' => '/treatment/',
		'/פרדס-חנה/תיקון-דיגרידו/' => '/repair/',
		'/פרדס-חנה/מדיטציית-דיגרידו-טקס-סאונד-הילינג/' => '/sound-healing/',
		'/פרדס-חנה/תיקים-וסטנדים-לדיגרידו-2/' => '/bags/',
		'/shop/books/וכתבת/' => '/books/vekatavta/',
		'/shop/books/כושי-בלאנטיס/' => '/books/kushi-blantis/',
		'/shop/books/כושי-בלנטיס/' => '/books/kushi-blantis/',
		'/shop/books/צבע-בכחול-וזרוק-לים/' => '/books/tsva-bekahol/',
		'/shop/books/שלושת-הספרים-וכתבתָּ-כושי-בלאנטיס-צב/' => '/books/',
		'/shop/books/שני-הספרים-וכתבתָּ-כושי-בלאנטיס-במחי/' => '/books/',
		'/דיגרידו-המרכז-לטיפול-בדיגרידו-סטודי/סאונד-הילינג-דיגרידו-מדיטציית-דיגרי/' => '/sound-healing/',
		'/Blog/הכל-אודות-ריברסינג-נשימה-מעגלית-ו-דיג/' => '/ריברסינג-נשימה-מעגלית-דיגרידו/',
		'/Blog/נשים-מנגנות-בדיגרידו-אישה-מנגנת-בדיג-2/' => '/נשים-מנגנות-בדיגרידו-אישה-מנגנת-בדיג/',
		'/Blog/סדנה-קבוצתית-מקיפה-וייחודית-לנשימה-מע/' => '/סדנת-דיגרידו-קבוצתית-מקיפה-וייחודית-ל/',
		'/Blog/את-הספר-החדש-שלי-לא-תמצאו-בחנויות-הספרי/' => '/את-הספר-החדש-שלי-לא-תמצאו-ברשתות-הספרים/',
		'/shop/cart/' => '/shop/',
		'/shop/checkout/' => '/shop/',
		'/shop/my-account/' => '/shop/',
	);

	// W2-06 blog migration: legacy /Blog/<slug> (capital B) -> /blog/<slug> (regex prefix;
	// the exact-match $map cannot express a prefix). Lowercase /blog/ won't match -> no loop.
	//
	// AN EXACT DECISION BEATS THE CATCH-ALL (WP-S5-03, 2026-07-16). The regex used to run
	// BEFORE $map and exit(), so an exact /Blog/<slug> rule was unreachable — the catch-all
	// always won. That silently dropped real content: a post RENAMED between the old and new
	// site got 301'd to /blog/<old-slug>, which 404s, because a prefix rewrite cannot follow a
	// rename. The full 406-URL triage found 4 live posts of Eyal's dead-ending exactly this way
	// (e.g. /Blog/את-הספר-החדש-שלי-לא-תמצאו-בחנויות-הספרי -> the live post is ...ברשתות...).
	// $map is now defined first and the regex yields to it. Do NOT reorder these back.
	if ( ! isset( $map[ $norm ] ) && preg_match( '#^/Blog/(.+)$#', $path, $m ) ) {
		header( 'X-EA-Redirect: w209-blog' );
		wp_redirect( home_url( '/blog/' . $m[1] ), 301 );
		exit;
	}
	if ( isset( $map[ $norm ] ) ) {
		header( 'X-EA-Redirect: w209-301' );
		wp_redirect( home_url( $map[ $norm ] ), 301 );
		exit;
	}
}
// priority 0: run before the site-tree canonical table (priority 1).
add_action( 'template_redirect', 'ea_w209_legacy_redirects', 0 );
