<?php
/**
 * One-time extractor: bank (block-faq-list.php) + local defaults → inc/data/ea-faq-seed.json
 * WP-CANON T2 — prefer local page copy where both exist (LOD400 §4.1).
 *
 * Usage: php scripts/extract_ea_faq_seed.php
 */

define( 'ABSPATH', true );

$root  = dirname( __DIR__ );
$theme = $root . '/site/wp-content/themes/ea-eyalamit';
$out   = $theme . '/inc/data/ea-faq-seed.json';

$local_slugs = array(
	'treatment',
	'sound-healing',
	'bags',
	'didgeridoos',
	'repair',
	'stands-storage',
	'stand-floor',
	'lessons',
	'method',
	'vekatavta',
	'kushi-blantis',
	'tsva-bekahol',
);

$defaults_map = array(
	'treatment'      => 'treatment-defaults.php',
	'sound-healing'  => 'sound-healing-defaults.php',
	'bags'           => 'bags-defaults.php',
	'didgeridoos'    => 'didgeridoos-defaults.php',
	'repair'           => 'repair-defaults.php',
	'stands-storage' => 'stands-storage-defaults.php',
	'stand-floor'    => 'stand-floor-defaults.php',
	'lessons'        => 'lessons-defaults.php',
	'method'         => 'method-defaults.php',
	'vekatavta'      => 'vekatavta-defaults.php',
	'kushi-blantis'  => 'kushi-blantis-defaults.php',
	'tsva-bekahol'   => 'tsva-bekahol-defaults.php',
);

function normalize_faq_answer( string $a ): string {
	$a = trim( $a );
	if ( '' === $a ) {
		return '<p></p>';
	}
	if ( preg_match( '/^<(p|ul|ol|div)\b/i', $a ) ) {
		return $a;
	}
	return '<p>' . $a . '</p>';
}

function parse_prose_faq_items( string $html ): array {
	$items = array();
	if ( ! preg_match_all( '/<p><strong>(.*?)<\/strong><\/p>\s*<p>(.*?)<\/p>/su', $html, $m, PREG_SET_ORDER ) ) {
		return $items;
	}
	foreach ( $m as $row ) {
		$items[] = array(
			'q' => html_entity_decode( strip_tags( $row[1] ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ),
			'a' => normalize_faq_answer( $row[2] ),
		);
	}
	return $items;
}

function parse_method_split_faq( string $body ): array {
	$items = array();
	if ( ! preg_match( '/<h3>שאלות נפוצות על השיטה<\/h3>(.*?)<h3>מה אנשים חווים לאורך הדרך<\/h3>/su', $body, $m ) ) {
		return $items;
	}
	$parts = preg_split( '/<p><strong>/', $m[1] );
	array_shift( $parts );
	foreach ( $parts as $part ) {
		if ( ! preg_match( '/^(.*?)<\/strong><\/p>(.*)$/su', $part, $pair ) ) {
			continue;
		}
		$items[] = array(
			'q' => html_entity_decode( strip_tags( $pair[1] ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ),
			'a' => trim( $pair[2] ),
		);
	}
	return $items;
}

function extract_faq_items_from_defaults( string $path, string $slug ): array {
	$data = include $path;
	if ( ! is_array( $data ) ) {
		return array();
	}
	if ( 'method' === $slug ) {
		return parse_method_split_faq( (string) ( $data['split_body'] ?? '' ) );
	}
	$sections = $data['sections'] ?? array();
	foreach ( $sections as $sec ) {
		$part = $sec['part'] ?? '';
		$args = $sec['args'] ?? array();
		if ( 'faq' === $part && ! empty( $args['items'] ) ) {
			return $args['items'];
		}
		if ( 'lessons' === $slug && 'prose' === $part && ( $args['title'] ?? '' ) === 'שאלות נפוצות' ) {
			return parse_prose_faq_items( (string) ( $args['body'] ?? '' ) );
		}
	}
	return array();
}

// Bank from block-faq-list.php (line slice — avoids fragile regex on 420-line array).
$block_lines = file( $theme . '/template-parts/blocks/block-faq-list.php' );
$slice = implode( '', array_slice( $block_lines, 34, 419 ) ); // lines 35–453.
$tmp         = sys_get_temp_dir() . '/ea-faq-bank-' . getmypid() . '.php';
file_put_contents( $tmp, '<?php return array(' . $slice . ');' );
$faq_data = include $tmp;
unlink( $tmp );

$seed_items = array();
$counters   = array();

// General (and any category without local override) from bank.
foreach ( $faq_data as $row ) {
	$cat = $row['category'];
	if ( in_array( $cat, $local_slugs, true ) ) {
		continue;
	}
	$counters[ $cat ] = ( $counters[ $cat ] ?? 0 ) + 1;
	$seed_items[]     = array(
		'seed_key'   => $cat . '-' . str_pad( (string) $counters[ $cat ], 2, '0', STR_PAD_LEFT ),
		'categories' => array( $cat ),
		'q'          => $row['q'],
		'a'          => $row['a'],
	);
}

// Local overrides (canonical per LOD400 §4.1).
foreach ( $defaults_map as $slug => $file ) {
	$path  = $theme . '/inc/chapters/defaults/' . $file;
	$local = extract_faq_items_from_defaults( $path, $slug );
	$counters[ $slug ] = 0;
	foreach ( $local as $item ) {
		$counters[ $slug ]++;
		$seed_items[] = array(
			'seed_key'   => $slug . '-' . str_pad( (string) $counters[ $slug ], 2, '0', STR_PAD_LEFT ),
			'categories' => array( $slug ),
			'q'          => $item['q'],
			'a'          => normalize_faq_answer( (string) $item['a'] ),
		);
	}
}

$payload = array(
	'_note'  => 'WP-CANON T2 seed — bank general + local page copy where both exist. Generated by scripts/extract_ea_faq_seed.php.',
	'count'  => count( $seed_items ),
	'items'  => $seed_items,
);

file_put_contents(
	$out,
	json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) . "\n"
);

echo "Wrote {$payload['count']} items to {$out}\n";
