#!/usr/bin/env python3
"""S007 work SSOT — schema lock, load, validate.

Source of truth: _COMMUNICATION/team_100/S007/S007-WORK-SSOT.json
Derived HTML is generated by s007_render_work_ssot.py. Do not hand-edit
status in the form or the Nimrod board.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SSOT_PATH = REPO / "_COMMUNICATION" / "team_100" / "S007" / "S007-WORK-SSOT.json"
SCHEMA = "s007-work-ssot-v1"

STATUSES = ("closed", "open", "waiting")
WAITING_ON = ("none", "eyal", "nimrod", "team10")
SURFACES = ("eyal_form", "nimrod_board", "both", "internal")
KINDS = ("content_gap", "visual", "a11y", "nav", "ops")

STAGING = "http://eyalamit-co-il-2026.s887.upress.link"


def load_ssot(path: Path = SSOT_PATH) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    errors = validate(data)
    if errors:
        raise SystemExit("SSOT invalid:\n  " + "\n  ".join(errors[:40]))
    return data


def sha12_bytes(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()[:12]


def sha12_path(path: Path) -> str:
    return sha12_bytes(path.read_bytes())


def validate(data: dict) -> list[str]:
    err: list[str] = []
    if data.get("schema") != SCHEMA:
        err.append(f"schema {data.get('schema')!r} != {SCHEMA}")
    if data.get("isWorkSsot") is not True:
        err.append("isWorkSsot must be true")
    items = data.get("items")
    if not isinstance(items, list) or not items:
        err.append("items must be a non-empty list")
        return err
    seen: set[str] = set()
    for i, it in enumerate(items):
        iid = it.get("id")
        prefix = f"items[{i}] {iid}"
        if not iid:
            err.append(f"items[{i}] missing id")
            continue
        if iid in seen:
            err.append(f"duplicate id {iid}")
        seen.add(iid)
        st = it.get("status")
        wo = it.get("waitingOn")
        sf = it.get("surface")
        kd = it.get("kind")
        if st not in STATUSES:
            err.append(f"{prefix}: bad status {st!r}")
        if wo not in WAITING_ON:
            err.append(f"{prefix}: bad waitingOn {wo!r}")
        if sf not in SURFACES:
            err.append(f"{prefix}: bad surface {sf!r}")
        if kd not in KINDS:
            err.append(f"{prefix}: bad kind {kd!r}")
        if st == "closed" and wo != "none":
            err.append(f"{prefix}: closed requires waitingOn=none")
        if st == "waiting" and wo == "none":
            err.append(f"{prefix}: waiting requires a waitingOn actor")
        if st == "closed":
            live = it.get("live") or {}
            if not live.get("check"):
                err.append(f"{prefix}: closed without live.check")
        eyal = it.get("eyal")
        if eyal is not None and not isinstance(eyal, dict):
            err.append(f"{prefix}: eyal must be object or null")
        nim = it.get("nimrod")
        if nim is not None and not isinstance(nim, dict):
            err.append(f"{prefix}: nimrod must be object or null")
    return err


def stamp_he(it: dict) -> str:
    """Hebrew chip for derived HTML. Always from SSOT fields, never invented in HTML."""
    custom = (it.get("stampHe") or "").strip()
    if custom:
        return custom
    st, wo = it["status"], it["waitingOn"]
    if st == "closed":
        return "נסגר באתר הבדיקה"
    if st == "waiting" and wo == "eyal":
        return "ממתין לך"
    if st == "waiting" and wo == "nimrod":
        return "ממתין לנימרוד"
    if st == "waiting" and wo == "team10":
        return "ממתין לצוות 10"
    if st == "open" and wo == "team10":
        return "פתוח אצל צוות 10"
    if st == "open":
        return "פתוח"
    return f"{st} / {wo}"


def live_url(path: str | None) -> str:
    if not path:
        return ""
    if path.startswith("http"):
        return path
    if not path.startswith("/"):
        path = "/" + path
    return STAGING + path
